<TapPointGame>:
#    Label:
#        text: "Hello World"

    canvas:
        Rectangle:
            pos: self.center_x-1, 0
            size: 2, self.height /2 - 60
        Rectangle:
            pos: self.center_x-1, self.height /2 + 60
            size: 2, self.height /2 - 60

    Label:
        font_size: 100
        center_x: root.width / 2
        center_y: root.height / 2
        text: str(int(root.points))

    Label:
        font_size: 70  
        center_x: root.width / 4
        top: root.top - 50
        text: str(root.player1)
        
    Label:
        font_size: 70  
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: str(root.player2)
    

