<TapPointGame>:
    #Left side
    canvas.before:
        Color:
            #Blue
            rgba: 0, 0, 0.75, 1 
        Rectangle:
            pos: 0, 0
            size: self.center_x, self.height

    #Right Side
        Color:
            #Red
            rgba: 0.75, 0, 0, 1 
        Rectangle:
            pos: self.center_x, 0
            size: self.center_x, self.height

    Label:
        font_size: 100
        center_x: root.width / 2
        center_y: root.height / 2
        text: str(int(root.points))

    Label:
        font_size: 70  
        center_x: root.width / 4
        top: root.top - 50
        text: str(root.player1)
        
    Label:
        font_size: 70  
        center_x: root.width * 3 / 4
        top: root.top - 50
        text: str(root.player2)
